// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelloStateful) DeepCopyInto(out *HelloStateful) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelloStateful.
func (in *HelloStateful) DeepCopy() *HelloStateful {
	if in == nil {
		return nil
	}
	out := new(HelloStateful)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HelloStateful) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelloStatefulList) DeepCopyInto(out *HelloStatefulList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HelloStateful, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelloStatefulList.
func (in *HelloStatefulList) DeepCopy() *HelloStatefulList {
	if in == nil {
		return nil
	}
	out := new(HelloStatefulList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HelloStatefulList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelloStatefulSpec) DeepCopyInto(out *HelloStatefulSpec) {
	*out = *in
	in.PersistentVolume.DeepCopyInto(&out.PersistentVolume)
	in.PersistentVolumeClaim.DeepCopyInto(&out.PersistentVolumeClaim)
	in.StatefulSet.DeepCopyInto(&out.StatefulSet)
	in.Service.DeepCopyInto(&out.Service)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelloStatefulSpec.
func (in *HelloStatefulSpec) DeepCopy() *HelloStatefulSpec {
	if in == nil {
		return nil
	}
	out := new(HelloStatefulSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelloStatefulStatus) DeepCopyInto(out *HelloStatefulStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelloStatefulStatus.
func (in *HelloStatefulStatus) DeepCopy() *HelloStatefulStatus {
	if in == nil {
		return nil
	}
	out := new(HelloStatefulStatus)
	in.DeepCopyInto(out)
	return out
}
